### CLOCK
#set_property PACKAGE_PIN W5 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#create_clock -add -name sys_clk -period 10.00 [get_ports clk]

### RESET (btnC)
#set_property PACKAGE_PIN U18 [get_ports rst]
#set_property IOSTANDARD LVCMOS33 [get_ports rst]

### BUTTONS
#set_property PACKAGE_PIN T18 [get_ports btnU]
#set_property IOSTANDARD LVCMOS33 [get_ports btnU]

#set_property PACKAGE_PIN U18 [get_ports btnC]
#set_property IOSTANDARD LVCMOS33 [get_ports btnC]

### SWITCHES
#set_property PACKAGE_PIN V17 [get_ports {switches[0]}]
#set_property PACKAGE_PIN V16 [get_ports {switches[1]}]
#set_property PACKAGE_PIN W16 [get_ports {switches[2]}]
#set_property PACKAGE_PIN W17 [get_ports {switches[3]}]
#set_property PACKAGE_PIN W15 [get_ports {switches[4]}]
#set_property PACKAGE_PIN V15 [get_ports {switches[5]}]
#set_property PACKAGE_PIN W14 [get_ports {switches[6]}]
#set_property PACKAGE_PIN W13 [get_ports {switches[7]}]
#set_property PACKAGE_PIN V2  [get_ports {switches[8]}]
#set_property PACKAGE_PIN T3  [get_ports {switches[9]}]
#set_property PACKAGE_PIN T2  [get_ports {switches[10]}]
#set_property PACKAGE_PIN R3  [get_ports {switches[11]}]
#set_property PACKAGE_PIN W2  [get_ports {switches[12]}]
#set_property PACKAGE_PIN U1  [get_ports {switches[13]}]
#set_property PACKAGE_PIN T1  [get_ports {switches[14]}]
#set_property PACKAGE_PIN R2  [get_ports {switches[15]}]

#set_property IOSTANDARD LVCMOS33 [get_ports switches[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[13]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[14]]
#set_property IOSTANDARD LVCMOS33 [get_ports switches[15]]

### LEDS
#set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
#set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
#set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
#set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
#set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
#set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
#set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
#set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
#set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
#set_property PACKAGE_PIN V3  [get_ports {leds[9]}]
#set_property PACKAGE_PIN W3  [get_ports {leds[10]}]
#set_property PACKAGE_PIN U3  [get_ports {leds[11]}]
#set_property PACKAGE_PIN P3  [get_ports {leds[12]}]
#set_property PACKAGE_PIN N3  [get_ports {leds[13]}]
#set_property PACKAGE_PIN P1  [get_ports {leds[14]}]
#set_property PACKAGE_PIN L1  [get_ports {leds[15]}]

#set_property IOSTANDARD LVCMOS33 [get_ports leds[0]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[1]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[2]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[3]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[4]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[5]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[6]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[7]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[8]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[9]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[10]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[11]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[12]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[13]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[14]]
#set_property IOSTANDARD LVCMOS33 [get_ports leds[15]]




## CLOCK
set_property PACKAGE_PIN W5 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.0 [get_ports clk]

## RESET (btnC)
set_property PACKAGE_PIN U18 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports rst]

## BUTTON (btnU)
set_property PACKAGE_PIN T18 [get_ports btnU]
set_property IOSTANDARD LVCMOS33 [get_ports btnU]

## SWITCHES (only SW0-SW10 used logically)
set_property PACKAGE_PIN V17 [get_ports {switches[0]}]
set_property PACKAGE_PIN V16 [get_ports {switches[1]}]
set_property PACKAGE_PIN W16 [get_ports {switches[2]}]
set_property PACKAGE_PIN W17 [get_ports {switches[3]}]
set_property PACKAGE_PIN W15 [get_ports {switches[4]}]
set_property PACKAGE_PIN V15 [get_ports {switches[5]}]
set_property PACKAGE_PIN W14 [get_ports {switches[6]}]
set_property PACKAGE_PIN W13 [get_ports {switches[7]}]
set_property PACKAGE_PIN V2  [get_ports {switches[8]}]
set_property PACKAGE_PIN T3  [get_ports {switches[9]}]
set_property PACKAGE_PIN T2  [get_ports {switches[10]}]

set_property IOSTANDARD LVCMOS33 [get_ports switches[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[4]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[5]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[6]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[7]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[8]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[9]]
set_property IOSTANDARD LVCMOS33 [get_ports switches[10]]

## LEDS
set_property PACKAGE_PIN U16 [get_ports {leds[0]}]
set_property PACKAGE_PIN E19 [get_ports {leds[1]}]
set_property PACKAGE_PIN U19 [get_ports {leds[2]}]
set_property PACKAGE_PIN V19 [get_ports {leds[3]}]
set_property PACKAGE_PIN W18 [get_ports {leds[4]}]
set_property PACKAGE_PIN U15 [get_ports {leds[5]}]
set_property PACKAGE_PIN U14 [get_ports {leds[6]}]
set_property PACKAGE_PIN V14 [get_ports {leds[7]}]
set_property PACKAGE_PIN V13 [get_ports {leds[8]}]
set_property PACKAGE_PIN V3  [get_ports {leds[9]}]
set_property PACKAGE_PIN W3  [get_ports {leds[10]}]
set_property PACKAGE_PIN U3  [get_ports {leds[11]}]
set_property PACKAGE_PIN P3  [get_ports {leds[12]}]
set_property PACKAGE_PIN N3  [get_ports {leds[13]}]
set_property PACKAGE_PIN P1  [get_ports {leds[14]}]
set_property PACKAGE_PIN L1  [get_ports {leds[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports leds[*]]