webtalk_init -webtalk_dir C:/Users/Administrator/Desktop/Ca Lab/project_ca_lab_6/project_ca_lab_6.sim/sim_1/behav/xsim/xsim.dir/lab6_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Mar  4 12:27:16 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dae7e245-bdc7-4a00-a9e3-1231f69f6842" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4eafde28569243eba11c2489d27d5524" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1190 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6696_KB" -context "xsim\\usage"
webtalk_transmit -clientid 408834679 -regid "" -xml C:/Users/Administrator/Desktop/Ca Lab/project_ca_lab_6/project_ca_lab_6.sim/sim_1/behav/xsim/xsim.dir/lab6_top_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Administrator/Desktop/Ca Lab/project_ca_lab_6/project_ca_lab_6.sim/sim_1/behav/xsim/xsim.dir/lab6_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Administrator/Desktop/Ca Lab/project_ca_lab_6/project_ca_lab_6.sim/sim_1/behav/xsim/xsim.dir/lab6_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
